version: "3.8"

services:
    client:
        image: des1nteresado/pet-store-client
        build:
            context: ./frontend
        ports:
            - "1387:80"
    server:
        image: des1nteresado/pet-store-server
        build:
            context: ./backend
        ports:
            - "8080:8080"
