version: '3.8'

services:
  # client:
  #     image: pet-store-client:prod
  #     build:
  #         context: ./frontend
  #         dockerfile: Dockerfile.prod
  #     ports:
  #         - "1387:80"
  server:
    image: pet-store
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
